### ISSUE TITLE
Can you double check how the sam file is created?

### ISSUE THREAD

**Issue by byee4** [shassathe/circRNA_eCLIP#1]
This read: `CGGGC:HWI-D00611:100:C6DB4ANXX:3:1115:12792:90810`

reports a flag that is unmapped (4) but contains a contig and position:

rep1/226_igf2bp2.sai.sam

**Comment by shassathe** [comment]
Sometimes bwa reports an 'unreliable' or 'chimeric' alignment as 'unmapped'. I believe that is what is happening. Ignore reads such as this. I would follow whatever 'flag' was assigned.
